# Generated by Django 3.0.5 on 2020-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhour',
            name='isAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
